### ISSUE TITLE
Error running `snazzy`

### ISSUE THREAD

**Issue by TuckerWhitehouse** [feross/snazzy#1]
I receive the following error when trying to run `snazzy` by itself, it works fine to run it as `standard --verbose | snazzy` but seems to have trouble spawning the child process.

``` bash
internal/child_process.js:298
    throw errnoException(err, 'spawn');
          ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:814:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:333:9)
    at Object.<anonymous> (C:\Program Files\iojs\node_modules\snazzy\bin\cmd.js:27:21)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
```

**Comment by tunnckoCore** [comment]
"I <3 stack traces, they are sooo useful. God to bless the man that invented them and in other side the devs that write 'proper and good' code." :+1: 

Which iojs version? I remember that 2.2 have a lot of bugs and lot things dont work on it. I dont seeing other reason - nodejs is okey with most of the platforms today, [so that](http://stackoverflow.com/questions/17516772/using-nodejss-spawn-causes-unknown-option-and-error-spawn-enoent-err) shouldn't be the reason.

**Comment by TuckerWhitehouse** [comment]
Sorry, Windows 8.1 and iojs 2.4.0

**Comment by tunnckoCore** [comment]
Dont sorry, it's not your fault. lol

> Windows 8.1 and iojs 2.4.0

than strange.. interesting. i cant help. Maybe again some of win weird bugs, that OS should die, lol.
It works here on latest arch, latest npm and iojs 2.4; and i use it.

**Comment by TuckerWhitehouse** [comment]
Work laptop... :-1: 

It looks like spawning anything other than a .cmd/.exe throws an error.
Everything works as expected if I replace the spawn line with `cp.spawn(require('path').resolve('./node_modules/.bin/standard')+'.cmd')`

It also seems to work if you spawn node with `STANDARD_CMD` as the first arg.

```
var args = process.argv.slice(2)
args.unshift(STANDARD_CMD)
var standard = cp.spawn('node', args)
```

**Comment by feross** [comment]
I just published 1.0.2 with a fix for Windows. https://github.com/feross/snazzy/commit/61ef41d31f5b72a3b7e09971fde2e284887a655c

@TuckerWhitehouse - please give it another try and confirm if it now works for you!

**Comment by djasnowski** [comment]
On a Windows 7 64-bit, I have this:

```
c:\wamp\www\navarra (master)
λ snazzy
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.<anonymous> (C:\Users\Dan\AppData\Roaming\npm\node_modules\snazzy\bin\cmd.js:27:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

I do have snazzy installed to 1.0.2 and just installed iojs and have nodejs to 0.12.7. Maybe it's just me, though.

**Comment by TuckerWhitehouse** [comment]
@feross no luck because there isn't a `standard.js.cmd` file in that directory. The .cmd file is created by npm and located at `./node_modules/.bin/standard.cmd`.

My suggestion for cross-platform support would be to spawn a node process, with `STANDARD_CMD` as the first argument:

``` javascript
var args = process.argv.slice(2)
args.unshift(STANDARD_CMD)
var standard = cp.spawn('node', args)
```

**Comment by feross** [comment]
Okay, this is actually fixed in snazzy 1.0.3. I just tested it on a windows machine.

Enjoy!

**Comment by TuckerWhitehouse** [comment]
Awesome, works great, thanks!

**Comment by feross** [comment]
Awesome!
