### ISSUE TITLE
Support version node 0.8.0 

### ISSUE THREAD

**Issue by tusharmath** [feross/snazzy#10]
I know its a very old version but a lot of legacy projects in production are using `0.8`. When they try to move to standard, their builds start to fail For example in https://github.com/lorenwest/node-config/pull/307 the standard integration breaks the build — https://travis-ci.org/lorenwest/node-config/builds/121860743

Its I think because of the way [inherits](https://github.com/isaacs/inherits) works for different versions of node.

**Comment by feross** [comment]
No problem. This was as simple as using `require('readable-stream')` instead of `require('stream')` since node 0.8 doesn't support streams2.

Released as 3.0.1.

**Comment by tusharmath** [comment]
@feross I am not sure if this will fix the problem. Check the stack trace —

``` stack
> standard | snazzy
util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at exports.inherits (util.js:538:43)
    at Object.<anonymous> (/home/travis/build/lorenwest/node-config/node_modules/snazzy/index.js:9:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/travis/build/lorenwest/node-config/node_modules/snazzy/bin/cmd.js:3:30)
    at Module._compile (module.js:449:26)
```

**Comment by feross** [comment]
Sorry, can't think of any reason why this won't work. Make sure you're actually using the latest version of `snazzy`. Otherwise, you're welcome to send a PR to fix this and I'll merge it.
